CREATE DATABASE datacredito;

USE datacredito;

CREATE TABLE clientes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    identificacion VARCHAR(20) NOT NULL UNIQUE,
    correo VARCHAR(255) NOT NULL,
    puntaje INT NOT NULL,
    fecha_ultima_consulta DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,       
  nombre VARCHAR(255) NOT NULL,            
  correo VARCHAR(255) NOT NULL UNIQUE,     
  login VARCHAR(120) NOT NULL,
  clave VARCHAR(255) NOT NULL,        
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
);
